spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9095/mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL;
      username: sa
      password:
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
  # elasticsearch
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org:
      hibernate.type.descriptor.sql.BasicBinder: TRACE
      springframework.data.elasticsearch.client.WIRE: TRACE

elasticsearch:
  config:
    ip: localhost
    port: 9200
